# Generated by Django 4.2.5 on 2023-11-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_project_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='No-Image.png', null=True, upload_to='project_thumbnail_images/'),
        ),
    ]
