# Generated by Django 4.2.5 on 2023-11-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_projectscheduleevent_delete_events'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectscheduleevent',
            table=None,
        ),
    ]
