# Generated by Django 4.2.5 on 2023-11-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_projectscheduleevent'),
        ('cms', '0013_alter_projectscheduleevent_table'),
    ]

    operations = [
    ]
