# Generated by Django 4.2.5 on 2023-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_merge_20231105_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscheduleevent',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
