# Generated by Django 4.2.5 on 2023-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_projectscheduleevent_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectscheduleevent',
            name='color',
        ),
    ]
